categories = ["Ruby", "JavaScript", "Testing", "SQL", "React", "API", "Deployment"]
description = [
  "<p class=\"ql-align-justify\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sodales bibendum congue. Sed sed imperdiet velit, vel varius nisi. Integer imperdiet elit vel tristique lobortis. Nullam tristique gravida libero sed condimentum. Donec ultricies erat velinterdum pellentesque. Donec auctor a nisl a vestibulum. Morbi convallis nunc sit amet nisi rhoncus, sit amet maximus justo egestas. Donec ullamcorper urna tortor, sit amet congue est consequat et. Pellentesque vel ante imperdiet, dapibus lorem id,ultrices magna. Suspendisse vehicula ligula sed aliquam volutpat. Suspendisse tortor velit, fringilla a neque in, condimentum blandit orci. Praesent consectetur suscipit quam et cursus.</p><p class=\"ql-align-justify\"></p><p class=\"ql-align-justify\">In consectetur mollis leo eget mattis. Proin ut bibendum mauris, a vestibulum mauris. Nulla vitae porttitor odio. Morbi a sem vulputate, convallis orci non, ultricies massa. Vestibulum non pulvinar purus. Etiam id quam vehicula massa porttitor varius.In dui tellus, lacinia quis suscipit sed, tincidunt vitae elit. Cras ullamcorper quam ac tincidunt convallis. Quisque lectus quam, hendrerit a tellus eget, ultrices egestas nunc. Aliquam mollis, libero ac cursus egestas, mi risus mollis enim, eu facilisisrisus nibh ac diam.</p><p class=\"ql-align-justify\"></p><ul><li class=\"ql-align-justify\">Donec auctor a nisl a vestibulum.</li><li class=\"ql-align-justify\">Aliquam mollis, libero ac cursus egestas, mi risus mollis enim, eu facilisis risus nibh ac diam.</li><li class=\"ql-align-justify\">Praesent consectetur suscipit quam et cursus.</li></ul><p class=\"ql-align-justify\"></p><p></p>",
  "<p class=\"ql-align-justify\">Vestibulum in magna eget erat eleifend vestibulum a euismod quam. Vivamus sit amet metus eget massa auctor sollicitudin. Pellentesque pulvinar non est non tincidunt. Aenean vitae viverra erat. Etiam accumsan, arcu vitae scelerisque hendrerit, dui mi iaculistortor, vel congue felis risus quis nunc. Maecenas ut sem dapibus, dignissim eros eu, congue ligula. Fusce ut diam non enim commodo scelerisque id id quam.</p><p class=\"ql-align-justify\"></p><ul><li><span style=\"color: rgb(0, 0, 0);\">Maecenas ac mauris eros.</span></li><li><span style=\"color: rgb(0, 0, 0);\">Etiam vel risus quis mauris sagittis ultricies. Vivamus maximus sagittis nunc ut iaculis. Sed odio urna, accumsan sed consequat at, vehicula eu quam. Pellentesque nulla libero, accumsan eget justo ac, gravida laoreet metus.</span></li></ul><p></p>",
  "<p class=\"ql-align-justify\"><strong style=\"font-size: large;\"><u>First Header</u></strong></p><p class=\"ql-align-justify\"><span style=\"font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; background-color: rgb(255, 255, 255);\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis non nisi est. Proin tempus, nisi eget finibus pellentesque, quam turpis consectetur purus, ac suscipit enim metus nec felis. Vestibulum risus lectus, cursus nec sagittis ac, iaculis egetmauris. Praesent vitae nulla turpis. Curabitur et volutpat enim, sed iaculis magna. Donec posuere orci at porttitor iaculis. Nam ut leo eu elit auctor sodales et sed ex. Morbi lacus urna, convallis ac leo sit amet, dapibus sagittis purus. Sedtristique aliquet risus at consectetur. In interdum velit in augue faucibus lacinia.</span></p><p class=\"ql-align-justify\"></p><p class=\"ql-align-justify\"><span style=\"font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; background-color: rgb(255, 255, 255);\">Suspendisse suscipit enim ut felis luctus molestie. Morbi at ultricies turpis. Vivamus felis tortor, volutpat vitae scelerisque eget, auctor eget ligula. Sed tincidunt lobortis purus ut pretium. Ut placerat aliquam rhoncus.</span></p><p class=\"ql-align-justify\"></p><p class=\"ql-align-justify\"><span style=\"font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; background-color: rgb(255, 255, 255);\">Etiam purus nisl, consequat in venenatis ullamcorper, laoreet at justo. Praesent a rutrum mauris. Integer molestie eros at nibh posuere elementum. Integer volutpat dapibus velit, vel semper mauris posuere a. Sed accumsan iaculis felis, id dictum nibhornare vestibulum. Curabitur vel pretium mi, et maximus mi. Aliquam erat volutpat. Curabitur pellentesque nibh hendrerit, placerat turpis in, laoreet ipsum. Mauris justo sem, blandit eu pretium venenatis, mattis vel nibh. Maecenas venenatis, augueac convallis iaculis, eros ipsum sagittis ipsum, et porta lectus dolor at justo. Suspendisse nec metus bibendum, lobortis lorem et, laoreet velit.</span></p><p class=\"ql-align-justify\"></p><p></p>"
]

user = User.create(email: 'user@test.com', password: 'password')
puts "User seeded, email: user@test.com, password: password."

25.times do
  opt1 = Faker::ParksAndRec.character
  opt2 = Faker::ElderScrolls.city
  opt3 = Faker::Cat.breed
  opt4 = Faker::SiliconValley.character
  titles = [opt1, opt2, opt3, opt4]
  
  user.companies.create(
    title: titles.sample,
    location: "#{Faker::Address.city}, #{Faker::Address.state_abbr}",
    description: description.sample
  )
end
puts "25 companies seeded."
